### ISSUE TITLE
Maintain data between VSim restarts

### ISSUE THREAD

**Issue by boemekeld** [BryanJacobs/FIDO2Applet#25]
Hey Bryan,

I'm trying to test your project through https://webauthn.io/, and I managed to do the "register" by adding the lines below to the build.gradle and executing "gradlew runVSim".

`task runVSim(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    main = 'us.q3q.fido2.VSim'
}`

My problem is that to execute the "Authenticate," I need to close and rerun the VSim class, and this causes the WebAuthN registration data to be lost.

Do you know how I can conduct this test? Is there a way to persist the data?

Thank you!

**Comment by BryanJacobs** [comment]
Why do you "need to close and rerun the VSim class"?

You should be able to send an authenticate command after sending a register without restarting in between.

No, there isn't any data persistence in the simulator :-).

**Comment by boemekeld** [comment]
Good question. It appears that Windows does not send the authentication command automatically.

![image](https://github.com/BryanJacobs/FIDO2Applet/assets/2818768/a703fb3e-a998-47b5-b4bc-beaef0c57e9c)

**Comment by BryanJacobs** [comment]
If Windows requires the authenticator to be de- and re-attached in order to be used, you're going to need some code simulating plugging in and unplugging the authenticator while keeping the software side running.

The relevant calls, private as they may or may not be, is `<Simulator>.driverProtocol.disconnect()` and then `.driverProtocol.connect(host, port)`.

If you munge the simulator field accessibility and call those methods _without_ calling `resetRuntime()`, you should have the applet state preserved but the virtual smartcard "removed" and then "reinserted" in the reader.

**Comment by boemekeld** [comment]
I'm trying to set up a development environment using your project and WebAuthN via browser. The plan is to extend it to support the ed25519 curve (for a Cardano Blockchain project).

**Comment by BryanJacobs** [comment]
That's an interesting idea.

If I were you, I would:

1. Making sure that the hardware you want to target actually supports eddsa keys, as I don't believe they're actually part of the Javacard standard until version 3.1 ( see https://docs.oracle.com/en/java/javacard/3.1/specnotes/index.html#GUID-ACB4D2F8-ADF9-4A23-9146-B4E5B73149D4 section 1.3.2 ), and to the best of my knowledge there are zero Javacard 3.1 devices on the market
2. Implement test code in `python_tests` that sends expected requests and fails. An example would be doing a makeCredential with the alg set to -8 (eddsa) instead of -7 (ecdsa-p256-sha256)
3. Fix the applet code so those tests pass (this will likely involve changing JCardSim, as, again, EdDSA isn't actually part of the Javacard 3.0 standard)
4. Test with command line tools like `fido2-cred`
5. Finally, progress to the point of using a web browser etc

I suspect number one will be a roadblock, but I'd be glad to help if I can.

**Comment by BryanJacobs** [comment]
Okay, I'll trust you know what you're doing.

I would recommend following the steps there. Your first development environment should probably be running the tests in the repository and having them pass. If you get that working, then you can write new tests for how you expect the modified applet to behave.

**Comment by boemekeld** [comment]
Yes, I was able to run the Python Tests successfully. However, I would like to be able to perform tests with a web browser before proceeding with the implementation of ed25519.

**Comment by BryanJacobs** [comment]
Okay. To reinsert the card as Windows seems to require will need you to change VSmartCard to expose the VSmartCardTCPProtocol object. At the point when you want to "reinsert" the card, close the connection and reopen it.

That's a much simpler change than making the applet handle different crypto protocols.

**Comment by boemekeld** [comment]
Alright, I'll try to do that. My reader only arrives next week. Thank you for your help.

**Comment by BryanJacobs** [comment]
No problem! I'll close this ticket, but feel free to let me know if you need any other help. Sorry about the state of VCardSim, I haven't been 100% happy with it myself :-/.
