### ISSUE TITLE
Backup options?

### ISSUE THREAD

**Issue by Toporin** [BryanJacobs/FIDO2Applet#27]
Hi,

I have been testing your applet recently, thanks for this impressive work!

I have a few questions that I could not find in the FAQ:

- What happens if I loose/break/brick my card? Are there recovery options?
- Is it possible to make a bakup of the applet state (resident keys,...)?
- If it is not (yet) possible to make a backup, could this be implemented in the future?
- What would be the minimum applet data to export to backup the card (to be able to recreate a new card with same credentials)?
- How many resident keys can be stored on a card typically? I guess it depends on the card: for example, I have NXP J3R110.
- Is it possible to get a list of the resident keys stored on the card, or delete a specific key, or get the available/total number of slots in the card
- Is there a command line/management tool to configure the card?

Sorry if I missed some answers in the documentation!

**Comment by BryanJacobs** [comment]
Glad you're enjoying the applet.

>  What happens if I loose/break/brick my card? Are there recovery options?

The only recovery option is to have a second (or third, or fourth) authenticator also registered to the same service(s). If you lose your card, you have lost the ability to authenticate with it.

> Is it possible to make a bakup of the applet state (resident keys,...)?

No. All keys are generated on the card and there is no way for them to leave it in a usable form.

> If it is not (yet) possible to make a backup, could this be implemented in the future?

The webauthn-3 standard describes a way to mark keys as "backup eligible" and inform sites when they have been backed up (to allow the site to reject the credential if it doesn't want you to do that...). The CTAP standards don't have a standard way to perform the backup, though. Also, there is a counter that's not allowed to go down that must be factored in - if you "restore" the key to a second authenticator, now you have two authenticators using the same key, and how do you sync the counter?

The answer is "yes, it's theoretically possible to implement a proprietary backup function, but that is not how FIDO2 authenticators are supposed to operate right now". FIDO2 by design is proof of something-you-have, and if you lose the thing you have, it doesn't make sense to be able to continue to authenticate with the same keys.

I'm not *against* implementing backups, but my preference is to wait until CTAP2.3 or something standardizes how they're done and makes them commonplace.

> What would be the minimum applet data to export to backup the card (to be able to recreate a new card with same credentials)?

Discoverable credential data, the master secrets for generating verifying/keys. Basically all the applet data stored in flash except maybe the LargeBlob store.

> How many resident keys can be stored on a card typically? I guess it depends on the card: for example, I have NXP J3R110.

For a nice large smartcard, hundreds, maybe even a thousand for the largest on the market. I have an "Apex Flex" where half the storage is taken up by a payment applet, and it still has room for 81 discoverable credentials. You can see how many - in the WORST case - could be stored by doing a `fido2-token -I` on the card and it will tell you how much room is left. It will get *at least* that many keys stored, and likely more, because the key size can vary and it uses the largest possible potential size to estimate remaining space.

The J3R110 - 110kB of storage - probably has room for between 100 and 200 discoverable credentials after installing the applet. To me that's a lot.

> Is it possible to get a list of the resident keys stored on the card, or delete a specific key, or get the available/total number of slots in the card

Yes to all, via standard CTAP2.1 commands. You must set and use a PIN to access these commands, as per the spec.

> Is there a command line/management tool to configure the card?

`fido2-token` from `libfido2` can do everything you just asked for above. So can my own took, `FIDOk`. I don't know of another command-line management tool other than those two. FIDOk also has a cross-platform GUI and an android app.

**Comment by Toporin** [comment]
It makes sense.
Thanks for the very clear explanations!

**Comment by harshd3shpande** [comment]
@BryanJacobs Piggybacking on this existing thread - I was wondering if an export function could be implemented that lets you export the resident keys if the applet is installed in "test mode". That way production keys don't break the FIDO standard and there is still a way to export keys for users who would like to experiment more.

Of course turning off test mode should erase all the stored keys.
