### ISSUE TITLE
Incorrect response on SELECT commands with unknown AID

### ISSUE THREAD

**Issue by StarGate01** [BryanJacobs/FIDO2Applet#32]
Once the applet is selected, it receives any subsequent commands, including further select commands.

For unknown / non-FIDO AIDs it should respond with `6a 82` *File not found* response code instead of `90 00`(success).

Rationale, we scan cards for installed applets by pinging each known AID. If the FIDO app is not properly rejecting unknown AIDs, it appears to the reader as if a subsequently pinged app is installed, despite it not being installed.

**Comment by BryanJacobs** [comment]
Fixed. Thanks, as always.

**Comment by lxgr** [comment]
Hi @BryanJacobs ,

Maybe I'm misunderstanding GlobalPlatform here, but was this change actually necessary/correct?

SELECT commands are always handled by the OPEN, not the currently active application (section 6.4.2.3 in GlobalPlatform v.2.3.1). Therefore, compliant cards should never send a subsequent selection command to this application, and the check should be redundant.

The problem is that, combined with the follow-up commit 8a7e18a79c2170b4259f4c4773187c1b38d6815d which hardcodes the expected AID, it now also breaks all scenarios where the AID does not exactly match the canonical FIDO2 one.

One use case for that is creating multiple instances on the same card, using that prefix and incrementing subsequent suffixes such as 001, 002 etc., which is a nice way of having multiple instances of the same (or a different) FIDO implementation on the same card, with all but one in the LOCKED state and the desired one selectively unlocked.

@StarGate01 are you aware of a GlobalPlatform/Java Card implementation that actually does forward subsequent SELECT commands to the active application, contrary to the GlobalPlatform spec? And even if there is one – wouldn't that mean that your logic

> we scan cards for installed applets by pinging each known AID

would now be broken the other way around, since you're essentially replacing a false positive (via the FIDO application potentially falsely/incorrectly claiming to be another application via a 9000 response to a subsequent SELECT) with a false negative (i.e. the FIDO application claiming to not be any other application, which would make your reader think that the other application is not installed, while it might well be)?

As an example, consider this application being installed as A001, and another one as A002: If you issue a SELECT A001, and then a SELECT A002, under your theory (the currently selected application gets to process subsequent SELECT commands), the applet would now return "no such file", and you'd believe there is no A002 installed, while you would be able to correctly select A002 as long as you do so before selecting A001.

Under my theory, the order actually does not matter, and the card/OPEN always processes SELECT commands and responds to/routes them accordingly. I unfortunately currently don't have the resources to test this myself.

Thank you!

**Comment by StarGate01** [comment]
@lxgr 
> are you aware of a GlobalPlatform/Java Card implementation that actually does forward subsequent SELECT commands to the active application, contrary to the GlobalPlatform spec? 

I cannot comment on the GP spec as I have not read it in its entirety, however the chips I work with (NXP P71D321 JCOP4) exhibit this behaviour, where subsequent SELECT commands are passed to the currently selected applet, but if and ONLY if the to-be-selected AID does not exists on the chip.

> a false negative

This is prevented by this mechanism. The targeted AID is actually installed, it is selected by the OPEN, instead of erroring out in the FIDO applet.

I am not quite happy with the way the AID is hardcoded, I have voiced my thoughts in #33 . However right now I don't see a real-world impact of this issue.

**Comment by lxgr** [comment]
Ah, I see, so it basically only happens when the "OPEN-side" SELECT fails. Thank you for confirming!

It seems like that's actually required by the specification:

> If no full or partial match is found at all, the currently selected Application on the Basic Logical Channel
shall remain the selected Application and [...] If the SELECT [by name] command has the [first or only occurrence] parameter set, the SELECT command is dispatched to the Application.

Seems like a weird quirk of the spec, and I can see how this could get confusing when enumerating applications without resetting the card/logical channel in between.

I also do share your concerns in #33 and will comment there. Thanks again!

**Comment by BryanJacobs** [comment]
"Theory is fine in theory, but practice is better in practice".

I don't want to reopen a real-world bug to better match a theoretical specification.

But I don't feel super strongly about suffixing the AID. I've pushed v2.0.5, which allows suffixed AIDs. You have a use case for them; enjoy. I haven't bothered adding the ability to fully customize the AID, but that should still suffice for testing.

**Comment by lxgr** [comment]
Thank you, appreciate it! Haven’t tested it yet but suffixes should do just fine.
